name: Build

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - '**/*.md'
    - provision.sh
    - Vagrantfile
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  # https://docs.brew.sh/Manpage#environment
  HOMEBREW_NO_ANALYTICS: 1
  HOMEBREW_NO_AUTO_UPDATE: 1
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            haxe: "4.2.5"
          - os: ubuntu-latest
            haxe: "4.3.7"
          - os: windows-latest
            haxe: "4.2.5"
          - os: windows-latest
            haxe: "4.3.7"
          - os: macos-latest
            haxe: "4.3.7"

    steps:
    - name: Git Checkout
      uses: actions/checkout@v6

    - name: Setup Haxe ${{ matrix.haxe }}
      uses: krdlab/setup-haxe@v2
      with:
        haxe-version: ${{ matrix.haxe }}
        cache-dependency-path: haxelib.json

    - name: Update brew formulas
      if: runner.os == 'macOS'
      run: |
        echo "::group::brew update" && brew update && echo "::endgroup::"
        echo "::group::brew config" && brew config && echo "::endgroup::"
        echo "::group::brew list" && brew list --version && echo "::endgroup::"

        # workaround to prevent "Error: The `brew link` step did not complete successfully" during "brew install mono"
        rm -f \
          /usr/local/share/man/man1/* \
          /usr/local/share/man/man5/* \
          /usr/local/bin/idle3 \
          /usr/local/bin/2to3 \
          /usr/local/bin/2to3 \
          /usr/local/bin/idle3 \
          /usr/local/bin/pydoc3 \
          /usr/local/bin/python3 \
          /usr/local/bin/python3-config

    - name: Set up Python 3
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Configure Python 3 on Windows
      if: runner.os == 'Windows'
      shell: cmd
      # workaround for https://github.com/actions/setup-python/issues/123
      run:
        if not exist "%pythonLocation%\python.exe" (
          mklink "%pythonLocation%\python3.exe" "%pythonLocation%\python.exe"
        )

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22

    - name: Setup lix
      run: npm i -g lix

    - name: Install haxe libs
      run: lix download

    - name: Build Travix
      shell: bash
      run: |
        haxe build-neko.hxml --lib hx3compat
        echo "HAXE_LIBS=--lib hx3compat" >> $GITHUB_ENV

    - name: Test Travix with [cs]
      run: lix run travix cs ${HAXE_LIBS:-}

    - name: Test Travix with [cpp]
      run: lix run travix cpp ${HAXE_LIBS:-}

    - name: Test [eval]
      run: lix run travix interp -D eval-stack ${HAXE_LIBS:-}

    - name: Test Travix with [hl]
      if: runner.os != 'Linux'
      run: lix run travix hl ${HAXE_LIBS:-}

    - name: Test Travix with [interp]
      run: lix run travix interp ${HAXE_LIBS:-}

    - name: Test Travix with [java]
      run: lix run travix java ${HAXE_LIBS:-}

    - name: Test Travix with [jvm]
      run: lix run travix java -D jvm ${HAXE_LIBS:-}

    - name: Test Travix with [lua]
      continue-on-error: ${{ runner.os != 'Linux' }}
      run: lix run travix lua ${HAXE_LIBS:-}

    - name: Test Travix with [neko]
      run: lix run travix neko ${HAXE_LIBS:-}

    - name: Test Travix with [node]
      run: lix run travix node ${HAXE_LIBS:-}

    - name: Test Travix with [php]
      run: lix run travix php ${HAXE_LIBS:-}

    - name: Test Travix with [python]
      run: lix run travix python ${HAXE_LIBS:-}
